### ISSUE TITLE
private_key var?

### ISSUE THREAD

**Issue by tehmaspc** [oracle/terraform-provider-baremetal#1]
What exactly should this - `variable "private_key" {}` TF var be? The full PEM key contents? Not sure here.

Trying to run the [vcn.tf](https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/network/simple_vcn/vcn.tf) example and I get the following error:

```
Error refreshing state: 1 error(s) occurred:

* PEM data was not found in buffer
```

Any help appreciated. Thanks!

**Comment by craigcarl-oracle** [comment]
@tehmaspc That's an alternative way to specify the key. If for any reason you don't want to use the `private_key_path` variable you can use `private_key`. You have to pick one, be sure to comment out the variable you aren't using. Comments in TF configurations are indicated by a # -

```# variable "private_key" {}```

If you want to to use `private_key` you can create the environment variable this way -
```export TF_VAR_private_key=$(cat /path/to/key)```

I'll clarify the docs and examples.

**Comment by tadakamalla** [comment]
I commented out the variable "private_key" {} and it worked. It still prompted me for key value while running the plan but I ignored it and just gave passphrase.

**Comment by tehmaspc** [comment]
@craigcarl-oracle - i think you still want to change this line - correct?:

https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/network/simple_vcn/vcn.tf#L11

to `private_key_path`?

**Comment by craigcarl-oracle** [comment]
@tehmaspc Yes I did :). Done.
