### ISSUE TITLE
baremetal_database_db_system does not support characterSet, ncharacterSet

### ISSUE THREAD

**Issue by jmajumde** [oracle/terraform-provider-baremetal#100]
## Description of the bug:
baremetal_database_db_system does not support characterSet, ncharacterSet

## A self-contained terraform file that reproduces the issue:

API supports this

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/database/20160918/requests/CreateDatabaseDetails

**Comment by craigcarl-oracle** [comment]
Fix expected from @mikejihbe this week.
