### ISSUE TITLE
Example docs need to refer env-vars instead of env-var

### ISSUE THREAD

**Issue by shubham023** [oracle/terraform-provider-baremetal#103]
## Description of the bug:
In README.md files for different examples, following is mentioned :

Update env-var with the required information. Most examples use the same set of environment variables so you only need to do this once.
    Source env-var
        $ . env-var

here filename should be env-vars instead of env-var. 

## A self-contained terraform file that reproduces the issue:
NA

Please let me know if I am correct in my understanding here. I would love to fix the docs, if this is really an issue.

**Comment by craigcarl-oracle** [comment]
@shubham023 Thanks for letting me know, I'll take care of it.
