### ISSUE TITLE
Simple vcn.tf plan fails with "provider.baremetal: asn1: structure error: tags don't match" 

### ISSUE THREAD

**Issue by craiganderson-53546** [oracle/terraform-provider-baremetal#114]
## Description of the bug:
Running Terraform 0.9.5 on Windows 7, with terraform-baremetal-provider downloaded from https://github.com/oracle/terraform-provider-baremetal/releases/windows.zip.  Environment is set by running env_vars manually resulting in...

C:\Users\canderson\Documents\Oracle IaaS\Terraform\block>env | grep TF
TF_VAR_compartment_ocid="ocid1.compartment.oc1..aaaaaaaadg43bsf6scab3pgoh45l74qufmatoux4t227eftxe2sdb6ur445q"
TF_VAR_fingerprint=2f:e6:97:a1:8a:8a:6c:b3:27:75:b8:60:0c:e0:c5:44
TF_VAR_private_key_path=C:\Users\canderson\Documents\Oracle IaaS\IaaS_CWA_3_pub.pem
TF_VAR_ssh_private_key=$(cat "C:\Users\canderson\Documents\Oracle IaaS\IaasCWA01.ppk")
TF_VAR_ssh_public_key=$(cat "C:\Users\canderson\Documents\Oracle IaaS\IaasCWA01.pub")
TF_VAR_SubnetOCID="ocid1.subnet.oc1.phx.aaaaaaaaa7h7lznvekfxufkflgts54du5x7eme5z4kyaw7hxaupp6fujmjgq"
TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaae6gjwjquxnwy57z5jsecp5cqxuzmrll6yaiwosh6vi33h6bg2pca
TF_VAR_user_ocid=ocid1.user.oc1..aaaaaaaa4tyf62exicss6lf4lg23qtgtyprl477thq4xief6tevfdoesllrq

Verified using TF_LOG=DEBUG that the correct provider file is used.  Running terraform plan from directory which holds only the vcn.tf file results in the error below...

Error running plan: 1 error(s) occurred:
* provider.baremetal: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEm
pty:false} int @2

## A self-contained terraform file that reproduces the issue:
used vcn.tf from https://github.com/oracle/terraform-provider-baremetal/tree/master/docs/examples/network/simple_vcn

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}

provider "baremetal" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

resource "baremetal_core_virtual_network" "a_TF_managed_VCN" {
  cidr_block = "10.0.0.0/16"
  dns_label = "vnc1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "a_TF_managed_VCN"
}

[vcn_debug.txt](https://github.com/oracle/terraform-provider-baremetal/files/1015281/vcn_debug.txt)

[vcn.tf.txt](https://github.com/oracle/terraform-provider-baremetal/files/1015283/vcn.tf.txt)

**Comment by craiganderson-53546** [comment]
Never mind.  Apparently I had one of the TF_VARs scrambled.  Although that leads me to say the error message does not help locate the error at all!  Sorry for the waste of bandwidth

**Comment by codycushing** [comment]
np
