### ISSUE TITLE
Simple vcn example fails with Code: NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by craiganderson-53546** [oracle/terraform-provider-baremetal#117]
## Description of the bug:
Trying to execute the ../docs/example/network/simple_vcn example using Terraform 0.9.5, latest copy of baremetal provider, running from Oracle Linux platform.  I have successfully executed this example from a Windows install using the same vars, keys, etc., which makes me think there I have the correct stuff in place.  The attached zip includes the debug output.  The error seems to point to the value of TF_VAR_private_key_path but 'cat $TF_VAR_private_key_path' looks valid, as does 'echo $TF_VAR_ssh_public_key' and same for public key.  Can you see what I am missing?
[vcn_issues.zip](https://github.com/oracle/terraform-provider-baremetal/files/1016182/vcn_issues.zip)

**Comment by devcamcar** [comment]
I'm also seeing this.

**Comment by craigcarl-oracle** [comment]
Dup of #64. There is a workaround described in that issue.

**Comment by devcamcar** [comment]
@craigcarl-oracle This does not appear to be a dupe of #64.  Very different error messages and this issue only crept up recently.  I believe it happened when I moved to 1.0.10 if I recall correctly.

**Comment by craiganderson-53546** [comment]
Error message is totally different as is the use case.  Issue #64 discusses building a subnet then trying to use it in the next build step, where a delay makes sense.  In simple-vcn building the vcn is the ONLY step.  The error indicates it cannot authenticate and no vcn is built.  I can execute 'ls -l $TF_VAR_private_key_path' so the file is accessible through the env var.
