### ISSUE TITLE
Single_Instance example fails with Invalid ssh public key type "$(cat"

### ISSUE THREAD

**Issue by craiganderson-53546** [oracle/terraform-provider-baremetal#118]
## Description of the bug:
I am trying to execute the ../docs/examples/compute/single-instance example using Terraform 0.9.5, latest copy of baremetal provider, running from a Windows 7 platform. I have successfully executed the simple_vcn example, which makes me think there I have the correct stuff in place.  But doing the single instance example from the same session it is not able to use the $TF_VAR_ssh_public_key or private variables.  That raises 2 questions in my mind: 1. Did the vcn example not use the ssh keys via the variables, 2. I don't think Windows command shell can handle '$()' construct in the set command.  The attached zip includes the debug output, tf files and the script I set up the environment with prior to running both examples. 

## A self-contained terraform file that reproduces the issue:
[single_inst_issue.zip](https://github.com/oracle/terraform-provider-baremetal/files/1016241/single_inst_issue.zip)

**Comment by craigcarl-oracle** [comment]
@craiganderson-53546 The examples work as written on OSX, *nix and I've been told they work in Windows 10 with WSL enabled. You can also replace `cat` with `setx`, see the [README](https://github.com/oracle/terraform-provider-baremetal/blob/master/README.md).

**Comment by craiganderson-53546** [comment]
setx would be replacement for export, not for the '${cat ' construct

**Comment by craiganderson-53546** [comment]
It does indeed work correctly under Windows 10 with WLS!  Thanks!  Perhaps the documentation should either provide a mechanism to pass the keys or simply state it is only supported on WLS.  I tried Win7/ Cygwin and could not get it to work
