### ISSUE TITLE
Support for ISCSI attachment response when creating a volume attachment.

### ISSUE THREAD

**Issue by jvcalise** [oracle/terraform-provider-baremetal#12]
In order to support automation of mounting volumes we need to add support to the Volume_Attachment resource to return the ISCSIVolumeAttachment reference.

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/IScsiVolumeAttachment/

**Comment by craigcarl-oracle** [comment]
@jvcalise I'm not sure what you are asking for. Do you want the volume_attachment resource to do a volume_attach and then a GET on IScsiVolumeAttachment, concatenate the results and return them as the attributes of volume_attach?

**Comment by jvcalise** [comment]
@craigcarl-oracle working from the perspective of the API volumeAttachment response is the base object response, but when I perform an ISCSI attachment I get back the subclass as a response, ISCSIVolumeAttachment.  This approach may be a bit difficult for TF to handle, so my ask here is to provide a specific ISCSI_Volume_Attachment resource, that returns the full ISCSI detail response.

**Comment by gansvv** [comment]
Would also be nice if TF could run the commands to ssh to iSCSI and maintain persistent connections between the instance and the volume through reboots. These commands show up in the console for each attached volume. 
If TF could just run these commands, it would make the attached volumes usable within the host immediately after provisioning the instances and volumes via TF.

**Comment by craigcarl-oracle** [comment]
@gansvv Yes, that will get added soon but you should only need to use it if you are using CHAP. If you are not using CHAP the best way to do this is auto-discovery of iSCSI LUNs using a script running in the instance (cron). 

An example - https://gist.github.com/craigcarl-oracle/555df3be506f8a54ce0757ddb44c4e5f
