### ISSUE TITLE
Invalid ssh public key type "-----BEGIN" in single_instance example

### ISSUE THREAD

**Issue by craiganderson-53546** [oracle/terraform-provider-baremetal#122]
## Description of the bug:
I am trying to execute the ../docs/examples/compute/single-instance example using Terraform 0.9.5, latest copy of baremetal provider, running from a Windows 10 WLS (bash) platform. I have successfully executed the simple-vcn example, which makes me think there I have the correct stuff in place. But doing the single instance example from the same session successfully creates the TFBlock and TFBlockAttachment, but then throws an error on the public key.  It appears to be valid and I can echo all the $TF_VARs and see the expected output.  The console session shows the full public key and it looks correct.  The console output from performing these steps (vcn followed by single-instance examples in same session) are in the zip file along with keys and tf files.
[block.zip](https://github.com/oracle/terraform-provider-baremetal/files/1023951/block.zip)

**Comment by craiganderson-53546** [comment]
Any progress or update on this?  Kinda wanna build some stuff!

**Comment by craiganderson-53546** [comment]
@codycushing Any progress or update on this? Kinda wanna _build_ some stuff!

**Comment by kocic11** [comment]
@craiganderson-53546 You should use SSH key pair, which is different from the provided RSA key pair. More information how to create SSH keys can be found [here](
https://docs.us-phoenix-1.oraclecloud.com/Content/Compute/Tasks/managingkeypairs.htm). 

Regards,
Aleksandar

**Comment by craiganderson-53546** [comment]
Absolutely correct!  Thank you!

**Comment by balaby25** [comment]
@craiganderson-53546 : did you get this working. 
i generated a new ssh-keygen keypair..but, still stuck with below 
* oci_core_instance.TFInstance: Status: 400; Code: InvalidParameter; OPC Request ID: /417...5C2; Message: Invalid format for ssh public key

**Comment by craiganderson-53546** [comment]
Yes, I got it working in both Win7 and Win10 Bash Shell.  I generated new public key in openssh format and private key in pem format.

**Comment by leeadh** [comment]
I also got the same problem. generated a new PUB and PEM/PPK . what's wrong?

**Comment by balaby25** [comment]
My mistake  was : in the authorized_keys , I had given the public key of a
different key pair.

**Comment by leeadh** [comment]
Managed to resolve. I realised my mistake: I made a mistake in my code.

**Comment by saiindian2** [comment]
I am also facing the same problem.  Kindly help
My tf file looks like below.
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}

variable "compartment_ocid" {}
variable "ssh_public_key" { default = "D:\\terraform\\oci.pub}
variable "ssh_private_key" { default = "D:\\terraform\\oci.ppk"}


Error: Error applying plan:

1 error(s) occurred:

* oci_core_instance.TFInstance: 1 error(s) occurred:

* oci_core_instance.TFInstance: Service error:InvalidParameter. Invalid format for ssh public key. http status code: 400

**Comment by kemila-codegen** [comment]
@saiindian2 did you find resolution for above error.
I also getting similar kind of error.


Error: Error applying plan:

1 error(s) occurred:

* oci_core_instance.web_instance: 1 error(s) occurred:

* oci_core_instance.web_instance: Service error:InvalidParameter. Invalid format for ssh public key. http status code: 400. Opc request id: 99ec822aa54e0764dea31f84fdb48458/F21253DB484C2E4B3F1984D6E667D6A0/11CF56253C3CA3D3D3B42A53D747B7D7

**Comment by kemila-codegen** [comment]
Can someone help on below error I am getting?

When we give plain text value of ssh key, its working fine.  
But it is not working when give the path of the key where exist. Please check commented lines those are the ways that I tried. 



variable "ssh_public_key" {
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4Og9GpSYbH6Pn5GdbObcprAwvFLJRHEt8uy6rtQjQH/apWggCjRHr3L0dN3VVeCmZhJMP3Io2/BOpg0cHgZtWyLPlCeQTP4x5yOa3PAS0FLw9ck3SKM/t1OXEn/LzXBQDRD2dh9j2w10aBBs9/ngb1V62lDz9+LNYn3bcoH4V9DZbk9kRnfMzxTW5nqGZMwy/CVgpeFGZbZ7obXBqhHMTPpzFYv503KYPmbKDdWlisncaGrG1limNyrZxE71C9Qa4c22wZMZTMiS2JshbDprTXRP1Ha+5PENGOdo/Pd8TWhqqUm6+EGCKZUOFbY4eBtg+eEKrIOIM7saQ+Nw2wDrtw== oracle"
  #default = "./userdata/public.pem"
  #default = "./userdata/web-instance-public.ppk"
  #default = "./userdata/ssh-key.pub"
  #default = "cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub"
  #default = "$(cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub)"

}

export TF_VAR_ssh_public_key= $(cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub)
