### ISSUE TITLE
User-Group Membership is destroyed and created again while re-running Terraform Apply

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-baremetal#123]
## Description of the bug:

User-Group membership is destroyed and re-created again for every terraform apply run despite of user being a member of the given group already.

**Comment by craigcarl-oracle** [comment]
Fix expected from @mikejihbe this week.

**Comment by mikejihbe** [comment]
I can't reproduce this. Please provide a complete terraform file that reproduces the problem.

**Comment by rahulviswam17** [comment]
[Terraform_iam.zip](https://github.com/oracle/terraform-provider-baremetal/files/1040299/Terraform_iam.zip)


Hi, 

I've attached my code here. Once users and groups are create, just re-run "terraform apply" again, you can see on the console it destroys the membership and creates it again. If this inference from the output message is incorrect, please correct me.

**Comment by mikejihbe** [comment]
There are multiple acceptance tests that show this works, so my guess is that this may have something to do with the enumeration going on in your example.

E.g. This works fine:
```
 resource "baremetal_identity_user" "u" {
	name = "user_name"
	description = "user desc"
    }
    resource "baremetal_identity_group" "g" {
	name = "group_name"
	description = "group desc"
    }
    resource "baremetal_identity_user_group_membership" "ug_membership" {
    	compartment_id = "${var.tenancy_ocid}"
	user_id = "${baremetal_identity_user.u.id}"
	group_id = "${baremetal_identity_group.g.id}"
    }
```

**Comment by rcohenma** [comment]
I couldn't reproduce this either.
If you think this is still an issue please reopen with more details.
