### ISSUE TITLE
How to add storage object to a bucket , is there a working example available ?

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-baremetal#125]
## Description of the bug:
Hi, 

How do I add storage object to a storage bucket. Is there a working example available using resource "baremetal_objectstorage_object" ?

**Comment by rahulviswam17** [comment]
Hi Craig , 

Could you please provide me with a sample code for this or update documentation with a sample code?

**Comment by gmflau** [comment]
Hi Craig,

I would love to see a sample code using "bmcs" CLI inside a BM or VM instance to CRUD an object in a bucket.

Thanks,
Gilbert

**Comment by codycushing** [comment]
Tracking in #225
