### ISSUE TITLE
Question: How to access attributes in local terraform statefile

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-baremetal#126]
## Description of the bug:
Hi All,
I have two folders (BE1 and BE2), I want to access the state file created in BE1 from BE2 From BE2, I can run "terraform state list/show/pull" commands, which means I can access the BE1's terraform state file. But can't use the variable in the main.tf of BE2.

Below is the example with BE1 and BE2 main.tf files. I've also attached my terraform.tfstate file for BE1 and 2.

## A self-contained terraform file that reproduces the issue:
[terraform_tfstate_BE2.txt](https://github.com/oracle/terraform-provider-baremetal/files/1027358/terraform_tfstate_BE2.txt)
[terraform_tfstate_BE1.txt](https://github.com/oracle/terraform-provider-baremetal/files/1027360/terraform_tfstate_BE1.txt)

-- Folder BE1---
JSYADAV@JSYADAV-LAP /cygdrive/c/Terraform/BE1

// file main.tf
## Create user1
resource "baremetal_identity_user" "tf_user1" {
  name        = "tf_user1"
  description = "A user I'm managing with Terraform "
}
## Output description of user1
output "description" {
  value = "${baremetal_identity_user.tf_user1.description}"

-- Folder BE1---
JSYADAV@JSYADAV-LAP /cygdrive/c/Terraform/BE2

// file main.tf
## Create Backend with config
terraform {
  backend "local" {
    path = "C:\\Terraform\\BE1\\terraform.tfstate"
  }
}
## declare the Data Source on the BE you want to use data "terraform_remote_state" "foo" {
  backend = "local"
  config {
    path = "C:\\Terraform\\BE1\\terraform.tfstate"
  }
}
## Access the data from data source. (both access variables are failing) <<<<< resource "baremetal_identity_user" "tf_user20" {
  name        = "tf_user20"
  description = "${data.terraform_remote_state.foo.output.description.value}"
  ##description = "${ data.terraform_remote_state.foo .baremetal_identity_user.tf_user1.description}"
}

**Comment by VAdamec** [comment]
Maybe use import? but that's not so straightforward solution. I'm using [Consul as variable storage / provider](https://www.terraform.io/docs/providers/consul/index.html). Not sure if it's useful/applicable solution for you.

**Comment by craigcarl-oracle** [comment]
@rahulviswam17 I'd suggest you ask in the TF Glitter room - https://gitter.im/hashicorp-terraform/Lobby
