### ISSUE TITLE
Creating a TCP lb_backendset fails with invalid SSL config error

### ISSUE THREAD

**Issue by jaoracle** [oracle/terraform-provider-baremetal#129]
## Description of the bug:
Terraform v0.9.4, baremetal-provider v1.0.11

Creating an LB with a backendset fails with the following error from terraform:
```
Error applying plan:

1 error(s) occurred:

* baremetal_load_balancer_backendset.lb-etcd-2379: 1 error(s) occurred:

* baremetal_load_balancer_backendset.lb-etcd-2379: Resource creation failed, state FAILED

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

In the dashboard the work requests shows an invalid SSL config error:
<img width="1070" alt="screen shot 2017-05-26 at 15 29 02" src="https://cloud.githubusercontent.com/assets/26151035/26511529/17df18ac-4228-11e7-858e-f160376e8d02.png">

Retry of the apply generates a crash:
[crash.log.zip](https://github.com/oracle/terraform-provider-baremetal/files/1032949/crash.log.zip)

## A self-contained terraform file that reproduces the issue:

[loadbalancers.tf.zip](https://github.com/oracle/terraform-provider-baremetal/files/1032912/loadbalancers.tf.zip)

**Comment by craigcarl-oracle** [comment]
@jaoracle This should be fixed [by 10c189a](https://github.com/oracle/terraform-provider-baremetal/commit/10c189a132de6bf30b5f963be0fbad83fe186303), the release [is here](https://github.com/oracle/terraform-provider-baremetal/releases/tag/v1.0.12), please test.
