### ISSUE TITLE
lb_listener fails with invalid SSL config error

### ISSUE THREAD

**Issue by jmajumde** [oracle/terraform-provider-baremetal#132]
## Description of the bug:
TF provider v1.0.12

baremetal_load_balancer_listener resource fails with ssl error in the work_req. No specific error message I see in the debug log

## A self-contained terraform file that reproduces the issue:

$ cat lbaaas_listener.tf 
{
  "resource": {
    "baremetal_load_balancer_listener": {
      "jmtfenv3-listener": {
        "load_balancer_id": "ocid1..........",
        "name": "jmtfenv3-listener",
        "default_backend_set_name": "jmtfenv3-backendset",
        "port": "8080",
        "protocol": "HTTP"
      }
    }
  }
}

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: jmtfenv3.plan

+ baremetal_load_balancer_listener.jmtfenv3-listener
    default_backend_set_name: "jmtfenv3-backendset"
    load_balancer_id:         "ocid1............."
    name:                     "jmtfenv3-listener"
    port:                     "8080"
    protocol:                 "HTTP"
    state:                    "<computed>"

Plan: 1 to add, 0 to change, 0 to destroy.
2017/05/30 20:22:49 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/30 20:22:49 [DEBUG] plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal: plugin process exited

$ terraform apply jmtfenv3.plan
2017/05/30 20:22:57 [INFO] Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
2017/05/30 20:22:57 [INFO] Go runtime version: go1.8
2017/05/30 20:22:57 [INFO] CLI args: []string{"/usr/bin/terraform", "apply", "jmtfenv3.plan"}
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] Attempting to open CLI config file: /home/opc/.terraformrc
2017/05/30 20:22:57 [INFO] CLI command args: []string{"apply", "jmtfenv3.plan"}
2017/05/30 20:22:57 [INFO] command: initializing local backend from plan (not set)
2017/05/30 20:22:57 [INFO] command: backend initialized: *local.Local
2017/05/30 20:22:57 [INFO] backend/local: starting Apply operation
2017/05/30 20:22:57 [INFO] terraform: building graph: GraphTypeApply
2017/05/30 20:22:57 [DEBUG] Resource state not found for "baremetal_load_balancer_listener.jmtfenv3-listener": baremetal_load_balancer_listener.jmtfenv3-listener
2017/05/30 20:22:57 [DEBUG] ReferenceTransformer: "baremetal_load_balancer_listener.jmtfenv3-listener" references: []
2017/05/30 20:22:57 [DEBUG] ReferenceTransformer: "provider.baremetal" references: []
2017/05/30 20:22:57 [DEBUG] Starting graph walk: walkApply
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "root"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "meta.count-boundary (count boundary fixup)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "provider.baremetal (close)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "baremetal_load_balancer_listener.jmtfenv3-listener" waiting on "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "meta.count-boundary (count boundary fixup)" waiting on "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "provider.baremetal (close)" waiting on "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "root" waiting on "meta.count-boundary (count boundary fixup)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "root" waiting on "provider.baremetal (close)"
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "baremetal_load_balancer_listener.jmtfenv3-listener", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "meta.count-boundary (count boundary fixup)", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "provider.baremetal (close)", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "root", sending new deps
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] dag/walk: walking "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] vertex 'root.provider.baremetal': walking
2017/05/30 20:22:57 [DEBUG] vertex 'root.provider.baremetal': evaluating
2017/05/30 20:22:57 [TRACE] [walkApply] Entering eval tree: provider.baremetal
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalInitProvider
2017/05/30 20:22:57 [DEBUG] plugin: starting plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal []string{"/home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal"}
2017/05/30 20:22:57 [DEBUG] plugin: waiting for RPC address for: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [INFO] terraform-provider-baremetal v1.0.12
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] plugin: plugin address: unix /tmp/plugin320911773
2017/05/30 20:22:57 [DEBUG] root: eval: terraform.EvalNoop
2017/05/30 20:22:57 [DEBUG] root: eval: terraform.EvalNoop
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalBuildProviderConfig
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSetProviderConfig
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalConfigProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalCompareDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalReadState
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalApplyPre
baremetal_load_balancer_listener.jmtfenv3-listener: Creating...
  default_backend_set_name: "" => "jmtfenv3-backendset"
  load_balancer_id:         "" => "ocid1.loadbalancer.oc1.h2atkua"
  name:                     "" => "jmtfenv3-listener"
  port:                     "" => "8080"
  protocol:                 "" => "HTTP"
  state:                    "" => "<computed>"
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalApply
2017/05/30 20:22:57 [DEBUG] apply: baremetal_load_balancer_listener.jmtfenv3-listener: executing Apply
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] No meta timeoutkey found in Apply()
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] Waiting for state to become: [SUCCEEDED_WORK_REQUEST SUCCEEDED FAILED]
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [TRACE] Waiting 200ms before next try
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [TRACE] Waiting 400ms before next try
2017/05/30 20:22:59 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:59 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:59 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:59 [TRACE] Waiting 800ms before next try
2017/05/30 20:23:00 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:00 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:23:00 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:00 [TRACE] Waiting 1.6s before next try
2017/05/30 20:23:02 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:02 [DEBUG] crud.BaseCrud.setState: state: "FAILED"
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalIf
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/05/30 20:23:02 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED
2017/05/30 20:23:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED
2017/05/30 20:23:02 [TRACE] [walkApply] Exiting eval tree: baremetal_load_balancer_listener.jmtfenv3-listener
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "provider.baremetal (close)"
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/05/30 20:23:02 [TRACE] Preserving existing state lineage "3671877d-31e2-4f3c-a0b0-3847b4806e1d"
Error applying plan:
2017/05/30 20:23:02 [DEBUG] plugin: waiting for all plugin processes to complete...

1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by codycushing** [comment]
Fixed in v1.0.13
