### ISSUE TITLE
Generated Load Balancer URI has wrong format and is unusable

### ISSUE THREAD

**Issue by nelsonse** [oracle/terraform-provider-baremetal#145]
[single_instance.zip](https://github.com/oracle/terraform-provider-baremetal/files/1069369/single_instance.zip)
## Description of the bug:
The built URL to retrieve the load balancer policies has an issue (double backslash):
 
https://iaas.us-phoenix-1.oraclecloud.com/20170115//loadBalancerPolicies?compartmentId=ocid1.compartment.oc1..aaaaaaaafsih5ewgjlzua3xaryxjbcefq7tpgjtb45mguu5craxjwdzntaia
 
Once I removed one backslash, I got the load balancer policies.
 
This is related to  github.com\oracle\terraform-provider-baremetal\vendor\github.com\MustWin\baremetal-sdk-go\url_builder.go file, buildLoadBalancerURL() method.

## A self-contained terraform file that reproduces the issue:

(If this is not provided, your ticket will be closed)

**Comment by codycushing** [comment]
Added in v1.0.13
