### ISSUE TITLE
core_security_list display_name change does not apply

### ISSUE THREAD

**Issue by beamanm** [oracle/terraform-provider-baremetal#158]
When trying to apply a change to a security list display name, provider code never applies it.  To 

###
###
resource "baremetal_core_virtual_network" "vnc-test" {
    cidr_block              = "10.10.10.0/30"
    compartment_id          = "YOUR TEST COMPARTMENT OCID HERE"
    display_name            = "vnc-test"
}
###
###
resource "baremetal_core_security_list" "test1" {
    compartment_id          = "YOUR TEST COMPARTMENT OCID HERE"
    display_name            = "test1"
    vcn_id                  = "${baremetal_core_virtual_network.vnc-test.id}"
    ingress_security_rules  = [
    ]
    egress_security_rules  = [
    ]
###
###
resource "baremetal_core_security_list" "test1" {
    compartment_id          = "YOUR TEST COMPARTMENT OCID HERE"
    display_name            = "test2"
    vcn_id                  = "${baremetal_core_virtual_network.vnc-test.id}"
    ingress_security_rules  = [
    ]
    egress_security_rules  = [
    ]
###
###
###
--------------------------------------------------------------------
display_name never applies, alway get change output like:

~ baremetal_core_security_list.test1
    display_name: "test1" => "test2"

**Comment by codycushing** [comment]
Fixed with #176, also effected route tables

**Comment by rcohenma** [comment]
fixed with v1.0.15

**Comment by beamanm** [comment]
excellent, thx!

On Fri, Jul 14, 2017 at 11:35 AM, Ramy Cohen Masri <notifications@github.com
