### ISSUE TITLE
Need file() interpolation around file_private_key_path

### ISSUE THREAD

**Issue by sfolkman** [oracle/terraform-provider-baremetal#16]
From complete_vcn/complete_vcn.tf
...
variable "private_key_path" {}
...

provider "baremetal" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  **private_key = "${file(var.private_key_path)}"**
}

**Comment by craigcarl-oracle** [comment]
@sfolkman In my testing it works both ways, what happens when you remove the file() interpolation?

**Comment by sfolkman** [comment]
Can't find variable 'private_key'
    
    On 3/8/17 2:31 PM, Craig Carl wrote:
    
    
      @sfolkman In my testing it works both
        ways, what happens when you remove the file() interpolation?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oracle/terraform-provider-baremetal","title":"oracle/terraform-provider-baremetal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/oracle/terraform-provider-baremetal"}},"updates":{"snippets":[{"icon":"PERSON","message":"@craigcarl-oracle in #16: @sfolkman In my testing it works both ways, what happens when you remove the file() interpolation?"}],"action":{"name":"View Issue","url":"https://github.com/oracle/terraform-provider-baremetal/issues/16#issuecomment-285191279"}}}

**Comment by craigcarl-oracle** [comment]
@sfolkman That's a different problem I think. Email me your configuration, I'll take a look.

**Comment by craigcarl-oracle** [comment]
Configuration issue.
