### ISSUE TITLE
Attaching a new Security List to a subnet causes destroy and rebuild, including that of DB

### ISSUE THREAD

**Issue by ramnathnayakpr** [oracle/terraform-provider-baremetal#163]
## Description of the bug:
Created three subnets without any specific security list attached to them and did terraform apply to build the entire topology which has a DB system.
Later added lines 122, 133 and 144 to explicitly attach a non-default Security List to the three subnets.
Doing an apply caused all three subnets to be destroyed and recreated including the DB System.
Expected behaviour: attaching a new security list should not cause a destroy and rebuild.

`  security_list_ids   = ["${baremetal_core_security_list.RetailSecList.id}"]`

## A self-contained terraform file that reproduces the issue:
[retail-sandbox.tf.zip](https://github.com/oracle/terraform-provider-baremetal/files/1097513/retail-sandbox.tf.zip)

(If this is not provided, your ticket will be closed)

**Comment by codycushing** [comment]
Currently the only non-destructive update operation on Subnets is mutating the DisplayName: https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/Subnet/UpdateSubnet

This means any other modification to the resource will result in destruction and creation of a new resource with the specified properties. 

The documentation should be improved to indicate which parameter changes will result in this behavior.

**Comment by ramnathnayakpr** [comment]
Here is the issue in a bit more detail:

I need to create a DB and allow traffic into the DB TNS port (by enabling a port in the sec list). But while creating VCN, I could not find a way to provide a custom security list, it just creates a default security list I have no control over. (Have I got this wrong, is there a way to provide a non-default custom sec list while creating the VCN?)

So I was forced to create a custom security list that permits the traffic I want to allow, but attaching this to the subnets causes the DB to be rebuilt. It should not rebuild the DB. With networking components the rebuild just creates a brief outage, which is tolerable, but rebuilding the DB causes the entire contents of the DB to be lost, which is a big issue.

**Comment by codycushing** [comment]
You can define custom security lists in a vcn through terraform and include them on the subnet resource during creation, that will avoid your issue. 

Have a look at this example: https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/load_balancer/lb_full/lb_full.tf#L84
