### ISSUE TITLE
CircleCI enabled?

### ISSUE THREAD

**Issue by gliptak** [oracle/terraform-provider-baremetal#166]
Is CircleCI enabled for this repo? I do see

https://github.com/oracle/terraform-provider-baremetal/blob/master/circle.yml

but PRs don't seem to have build validation.

Thanks

**Comment by gliptak** [comment]
@eginez @codycushing Please let me know ig a TravisCI setup is of interest. Thans

**Comment by eginez** [comment]
Yeah that would be useful. I haven't worked with TravisCI much to be honest, not sure what it take to integrate it

**Comment by gliptak** [comment]
I can create the TravisCI YAML file for the project, but for both CircleCI and TravisCI an organization (admin?) will have to complete some minimal configuration on their respective websites (to build master on pushes, to build PRs, etc).

**Comment by eginez** [comment]
You know that would be great, if you send us a PR I'll be happy to look at it. We'll go from there

**Comment by codycushing** [comment]
Thanks for the work, we have werker integration now
