### ISSUE TITLE
tests need to be fixed

### ISSUE THREAD

**Issue by rcohenma** [oracle/terraform-provider-baremetal#171]
1. Some Acceptance tests are failing
2. Unit tests
There are some compilation errors with the mock client that i fixed easily but i still get errors when i run the unit tests

go test

--- FAIL: TestResourceShowConsoleHistory (0.02s)
        testing.go:280: Step 0 error: Configuration is invalid.
                
                Warnings: []string(nil)
                
                Errors: []string{"data.baremetal_core_policies.policies: Provider doesn't support data source: baremetal_core_policies", "data.baremetal_core_protocols.protocols: Provider doesn't support data source: baremetal_core_protocols"}
--- FAIL: TestCoreInstanceConsoleHistoriesDatasource (0.02s)
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
        Either do Mock.On("CreateCpe").Return(...) first, or remove the CreateCpe() call.
        This method was unexpected:
                CreateCpe(string,string,*baremetal.CreateOptions)
                0: "compartment_id"
                1: "142.10.10.2"
                2: &baremetal.CreateOptions{RetryTokenOptions:baremetal.RetryTokenOptions{RetryToken:""}, DisplayNameOptions:baremetal.DisplayNameOptions{DisplayName:"name1"}}
        at: [bare_metal_client.go:192 resource_obmcs_core_cpe.go:103 helpers.go:175 resource_obmcs_core_cpe.go:57 resource.go:186 provider.go:242 eval_apply.go:57 eval.go:53 eval_sequence.go:14 eval.go:53 eval.go:34 graph.go:126 walk.go:387 asm_amd64.s:2197]

goroutine 887 [running]:
github.com/oracle/terraform-provider-baremetal/vendor/github.com/stretchr/testify/mock.(*Mock).Called(0xc42056a380, 0xc4201d9e00, 0x3, 0x3, 0x100, 0xc420430780, 0x18aa580)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/stretchr/testify/mock/mock.go:306 +0x967
github.com/oracle/terraform-provider-baremetal/client/mocks.(*BareMetalClient).CreateCpe(0xc42056a380, 0xc42050e820, 0xe, 0xc420227481, 0xb, 0xc42051a480, 0x248b440, 0x1054cf0, 0x20083e0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/client/mocks/bare_metal_client.go:192 +0x155
github.com/oracle/terraform-provider-baremetal.(*CpeResourceCrud).Create(0xc42051a3a0, 0x19449e0, 0x2)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_core_cpe.go:103 +0x1cd
github.com/oracle/terraform-provider-baremetal/crud.CreateResource(0xc420518540, 0x1fcdba0, 0xc42051a3a0, 0x248b440, 0xc42056a380)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:175 +0x49
github.com/oracle/terraform-provider-baremetal.createCpe(0xc420518540, 0x1a18560, 0xc42056a380, 0x0, 0xc4202635e8)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_core_cpe.go:57 +0xe0
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42043bc20, 0xc4204323c0, 0xc42051a100, 0x1a18560, 0xc42056a380, 0xc420314101, 0x34, 0x0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4200ab490, 0xc4201d7f40, 0xc4204323c0, 0xc42051a100, 0x1, 0xd0f0b062, 0x0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.(*EvalApply).Eval(0xc42050cb40, 0x1fd2260, 0xc42034a000, 0x2, 0x2, 0x1a1afcd, 0x4)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/eval_apply.go:57 +0x232
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x1fc2560, 0xc42050cb40, 0x1fd2260, 0xc42034a000, 0x0, 0x0, 0x0, 0x0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc420447bc0, 0x1fd2260, 0xc42034a000, 0x2, 0x2, 0x1a1afcd, 0x4)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x1fc2f20, 0xc420447bc0, 0x1fd2260, 0xc42034a000, 0x18ea8e0, 0xc420451fca, 0x18aa580, 0xc42050e0e0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.Eval(0x1fc2f20, 0xc420447bc0, 0x1fd2260, 0xc42034a000, 0xc420447bc0, 0x1fc2f20, 0xc420447bc0, 0xc42003cbe0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x19d1780, 0xc4202a6b68, 0x0, 0x0)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc4202cda40, 0x19d1780, 0xc4202a6b68, 0xc420347480)
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
        /Users/rcohenma/GoglandProjects/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca
exit status 2
FAIL    github.com/oracle/terraform-provider-baremetal  0.055s

**Comment by josephholsten** [comment]
I'll look at this today

**Comment by codycushing** [comment]
Console Histories test fixed in #218

**Comment by codycushing** [comment]
Tracking as a different test refactor ticket
