### ISSUE TITLE
search_domain_names option will not apply

### ISSUE THREAD

**Issue by beamanm** [oracle/terraform-provider-baremetal#180]
In "baremetal_core_dhcp_options" resource, search_domain_names option will plan but not build.  It fails with error below.  Terraform config provided below, if you need the VCN/compartment builds let me know I'll provide those, for now I've left them as "".

thx,

-marcus

-----------------------------------------------------------------------------------------
--  plan work, apply fails with:
-----------------------------------------------------------------------------------------
Error applying plan:

1 error(s) occurred:

* baremetal_core_subnet.oragit-phx1-net-vnc1-ad3-prod-tools-dns-internal-mt1: 1 error(s) occurred:

* baremetal_core_subnet.oragit-phx1-net-vnc1-ad3-prod-tools-dns-internal-mt1: Code: NotAuthorizedOrNotFound; OPC Request ID: /F864963327084809AEECFA039E80A818/98C5B38583C3434AB075290B2FA65C9E; Message: Either Subnet with ID ocid1.compartment.oc1..aaaaaaaarsx6e76l7sjo5zooxd4l6rbifosgzgcqq54pyoreozlzpzupufua does not exist or you are not authorized to access it.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

-----------------------------------------------------------------------------------------
--  terraform
-----------------------------------------------------------------------------------------
resource "baremetal_core_dhcp_options" "test-dhcp1" {
  compartment_id            = ""
  vcn_id                    = ""
    display_name            = "test-dhcp1"
    options {
         type               = "DomainNameServer"
         search_domain_names= [ "test.com" ]
         server_type        = "CustomDnsServer"
         custom_dns_servers = [ "192.168.0.2", "192.168.0.11", "192.168.0.19" ]
         }
}

resource "baremetal_core_subnet" "test-subnet1" {
    availability_domain       = "gGeX:PHX-AD-1"
    cidr_block                = "192.168.100.0/24"
    compartment_id            = ""
    dhcp_options_id           = "${baremetal_core_dhcp_options.test-dhcp1.id}"
    display_name              = "test-subnet1"
    vcn_id                    = ""
    route_table_id            = ""
    security_list_ids         = []
}

------------------------------------------------------------------------------------------------

**Comment by codycushing** [comment]
It's not obvious from the api docs, but this feature requires passing two dns options, and would be structured in a terraform plan like this:
```
resource "baremetal_core_dhcp_options" "dhcp-options" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${var.vcn_ocid}"
  display_name = "dhcp-options"

  options {
    type = "DomainNameServer"
    server_type = "CustomDnsServer"
    custom_dns_servers = [ "192.168.0.2", "192.168.0.11", "192.168.0.19" ]
  }

  options {
    type = "SearchDomain"
    search_domain_names = [ "test.com" ]
  }
}
```

I'll update the docs/examples to include this.

**Comment by codycushing** [comment]
#216
