### ISSUE TITLE
Node from one region can't communicate to a node in another region over public IP addresses

### ISSUE THREAD

**Issue by gmflau** [oracle/terraform-provider-baremetal#185]
## Description of the bug:
The multi-vcn-region example is great - https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/vcn_multi_region/vcn_multi_region.tf .  However, node in one region cannot communicate (in my case, ssh into) to a node in another region over public IP addresses.

## A self-contained terraform file that reproduces the issue:
https://github.com/DSPN/oracle-bmc-terraform-dse/blob/multi-dc/network.tf
You can use the above network.tf to provision the corresponding networks in us-phoenix-1 and us-ashburn-1 regions.  Then create one VM instance in each region to reproduce the issue.

**Comment by codycushing** [comment]
This would be a problem with your network configuration, how you are launching instances or how you are trying to ssh, not actually a bug in the provider. Without specifics on the last two we can't really help.

**Comment by codycushing** [comment]
Feel free to comment with more specifics if you think this is terraform/provider related.
