### ISSUE TITLE
typo showing baremetal_identity_compartment ?

### ISSUE THREAD

**Issue by gliptak** [oracle/terraform-provider-baremetal#189]
The row labeled compartment_id shows the tenancy ocid. Would this label be incorrect? Thanks

```
λ terraform show
baremetal_identity_compartment.xxxxx:
  id = ocid1.compartment.oc1..xxxxx
  compartment_id = ocid1.tenancy.oc1..xxxxx
  description = xxxxx
  name = xxxxx
  state = ACTIVE
  time_created = 2017-07-21 xx:06:13.513 +0000 UTC
```

**Comment by codycushing** [comment]
Agreed it's a little misleading, this is a provision for supporting nested compartments--the tenancy is used as the root compartment.

**Comment by gliptak** [comment]
@codycushing Maybe ```parent_compartment_id``` would be a more descriptive name? Thanks
