### ISSUE TITLE
VCN default_route_table_id documentation issue

### ISSUE THREAD

**Issue by kristenjacobs** [oracle/terraform-provider-baremetal#19]
The default route/routing table attribute of the baremetal_core_virtual_networks resource is documented to be 'default_route_table_id'. However, looking at the code, it looks like it should be 'default_routing_table_id'.

**Comment by craigcarl-oracle** [comment]
@kristenjacobs Got it, thanks.

**Comment by craigcarl-oracle** [comment]
Fixed by #41
