### ISSUE TITLE
dhcp_options_id: required field is not set

### ISSUE THREAD

**Issue by andytael** [oracle/terraform-provider-baremetal#191]
## Description of the bug:
In the examples the dhcp_options_id is missing when creating a subnet (resource "baremetal_core_subnet")
If this option is not set this error is thrown:
* baremetal_core_subnet.TFTestSubnetAD1: "dhcp_options_id": required field is not set

I don't know what this should be set to, can you point me to documentation?

## A self-contained terraform file that reproduces the issue:
resource "baremetal_core_subnet" "TFTestSubnetAD1" {
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.ADs.availability_domains[0],"name")}"
  cidr_block = "10.0.1.0/24"
  display_name = "TFTestSubnet"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
  security_list_ids = ["${baremetal_core_security_list.WebSubnet.id}"]
  dhcp_options_id = "${baremetal_core_virtual_network.TFTestVCN.default_dhcp_options_id}"
}
(If this is not provided, your ticket will be closed)

**Comment by gliptak** [comment]
https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/resources/core/subnet.md specifies:
```dhcp_options_id``` - (Required) The OCID of the set of DHCP options the subnet will use.

**Comment by codycushing** [comment]
Examples updated with default dhcp options usage
