### ISSUE TITLE
refreshing manually deleted VCN takes long

### ISSUE THREAD

**Issue by gliptak** [oracle/terraform-provider-baremetal#195]
Create VCN using https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/network/simple_vcn/vcn.tf

Refresh takes ~1 second:

```
Î» time terraform refresh
baremetal_core_virtual_network.VCN_1: Refreshing state... (ID: ocid1.vcn.oc1.phx.zzzzzzzz)

real    0m1.118s
user    0m0.000s
sys     0m0.015s
```

After deleting from VCN console, the refresh takes ~2 minutes:

```
Î» time terraform refresh
baremetal_core_virtual_network.VCN_1: Refreshing state... (ID: ocid1.vcn.oc1.phx.zzzzzzzz)

real    2m1.893s
user    0m0.000s
sys     0m0.046s
```

**Comment by rcohenma** [comment]
see issue #179

**Comment by codycushing** [comment]
Thanks for the data. Closing as dup, using #179 as tracking ticket for retry logic improvement to mitigate destroy perf issue.
