### ISSUE TITLE
* baremetal_core_virtual_network.a_TF_managed_VCN: unexpected EOF

### ISSUE THREAD

**Issue by tadakamalla** [oracle/terraform-provider-baremetal#2]
I am running into this issue consistently across all the sample code I tried. Anything that I am doing wrong ?

* baremetal_core_virtual_network.a_TF_managed_VCN: unexpected EOF
2017/02/17 07:55:04 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_core_virtual_network.a_TF_managed_VCN: unexpected EOF
2017/02/17 07:55:04 [TRACE] [walkApply] Exiting eval tree: baremetal_core_virtual_network.a_TF_managed_VCN
2017/02/17 07:55:04 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "baremetal_core_virtual_network.a_TF_managed_VCN"
2017/02/17 07:55:04 [TRACE] Preserving existing state lineage "3edcbd6a-a5e0-4413-ab78-2b217c5774e3"
2017/02/17 07:55:04 [TRACE] Preserving existing state lineage "3edcbd6a-a5e0-4413-ab78-2b217c5774e3"
2017/02/17 07:55:04 [DEBUG] plugin: waiting for all plugin processes to complete...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by tadakamalla** [comment]
BTW, this is happening while I am trying to apply.

**Comment by sivaedupuganti-oracle** [comment]
This could happen when you provide an empty string for _private_key_ variable. Make sure to set the environment variable to the content of the key file. 
`> export TF_VAR_private_key=$(cat /full/path/to/key.pem)`

Instead, you can use the _private_key_path_ variable and provide the **full** path to the key file.  
`> export TF_VAR_private_key_path=/full/path/to/key.pem`

You only need to set one of these env variables. Whichever one you chose, make sure to use the same variable in the tf config file. In my case, I chose _private_key_path_ 
```
$ cat simple_vcn/vcn.tf 
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "**private_key_path**" {}
variable "compartment_ocid" {}

provider "baremetal" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  **private_key_path= "${var.private_key_path}"**
}
 
...
```

When I run `terraform plan simple_vcn`, it prompts for the `private_key`, but its optional. Just press enter and continue.
```
provider.baremetal.private_key
  (Optional) A PEM formatted RSA private key for the user.
  A private_key or a private_key_path must be provided.

  Enter a value: <press enter>

provider.baremetal.private_key_password
  (Required) The password used to secure the private key.
```

**Comment by tadakamalla** [comment]
Thank you, ti worked with out private_key_password ! I initially had private_key_password as I encountered an error while running apply from a .plan file..

provider.baremetal: "private_key_password": required field is not set
 Now I can apply without a plan file and successfully created the resource, but I am still running into required field not set when I use a plan file. Thanks for your help !

**Comment by craigcarl-oracle** [comment]
Thanks Siva!
