### ISSUE TITLE
 How to create different Security List applied to different instances in the same subnet? 

### ISSUE THREAD

**Issue by AudreyBramy** [oracle/terraform-provider-baremetal#202]
## Description of the bug:
In the same subnet I would like to create instances with different security rules.   For instance, in a public subnet, a bastion and a NAT instance doesn't have the same security rules.  I can't find a why to create security rules applied at the instance level.

## A self-contained terraform file that reproduces the issue:

The NAT security list
resource "baremetal_core_security_list" "NatSeclist" {
    compartment_id = "${var.compartment_ocid}"
    display_name = "nat"
    vcn_id = "${baremetal_core_virtual_network.vcn.id}"
    egress_security_rules = [{
	      protocol = "6"
        destination = "0.0.0.0/0"
    }]
    ingress_security_rules = [{
	      protocol = "6"
        source = "${var.VPC-CIDR}"
    }]
}

And the Bastion Security List:
resource "baremetal_core_security_list" "BastionSubnet" {
    compartment_id = "${var.compartment_ocid}"
    display_name = "Bastion"
    vcn_id = "${baremetal_core_virtual_network.vcn.id}"
    egress_security_rules = [{
	      protocol = "6"
        destination = "0.0.0.0/0"
    }]
    ingress_security_rules = [{
        tcp_options {
            "max" = 22
            "min" = 22
        }
        protocol = "6"
        source = "0.0.0.0/0"
    },{
	      protocol = "6"
        source = "${var.VPC-CIDR}"
    }]
}

**Comment by codycushing** [comment]
Unfortunately, what you are trying to do is not supported from the [overview doc](https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Concepts/securitylists.htm)

> ... you configure your security lists at the subnet level, which means that all instances in a given subnet are subject to the same set of rules

So to apply different security lists to different instances you will need the instances to reside on different subnets.
