### ISSUE TITLE
Terraform Script to create multiple Instances in the different subnets

### ISSUE THREAD

**Issue by tanujchinnu** [oracle/terraform-provider-baremetal#207]
Hi,

I'm using the below URL code, to create windows server https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/compute/windows/windows.tf I would like to create 2 instances using the same code in two different subnets. How can I do that?

**Comment by gliptak** [comment]
Convert the example ```tf``` into a ```Terraform``` ```module``` with ```subnet_ocid``` as input.

https://www.terraform.io/docs/modules/index.html

**Comment by tehmaspc** [comment]
if there is a place to contribute BMC TF modules - I'd be happy to contribute my modules back to the community.

**Comment by codycushing** [comment]
There is an actual initiative to create a modules repository but that will likely be some time out. You can create pull requests with your own samples if you would like, too.
