### ISSUE TITLE
Terraform destroy doesnt delete created resources on lb_full

### ISSUE THREAD

**Issue by jibsonline** [oracle/terraform-provider-baremetal#208]
## Description of the bug:
The below example creates all the resources well. But a terraform destroy doesn't' delete the resources created.

https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/examples/load_balancer/lb_full/lb_full.tf 

Output : 

#terraform.exe destroy

Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

data.baremetal_core_images.image-list: Refreshing state...
data.baremetal_identity_availability_domains.ADs: Refreshing state...
data.baremetal_core_images.image-list: Destroying... (ID: 2017-08-04 07:12:13.3351744 +0000 UTC)
data.baremetal_core_images.image-list: Destruction complete
data.baremetal_identity_availability_domains.ADs: Destroying... (ID: 2017-08-04 07:12:13.3031726 +0000 UTC)
data.baremetal_identity_availability_domains.ADs: Destruction complete

Destroy complete! Resources: 2 destroyed.

**Comment by codycushing** [comment]
We recently tested and were not able to reproduce. Can you check the console for any failed work requests related to this destroy scenario?

**Comment by briangustafson** [comment]
I've also tried reproing and have not seen this issue. Are you seeing it consistently? 

If you could set "TF_LOG=DEBUG" and "DEBUG=true", rerun apply and then destroy and send the output, that would be very helpful.

**Comment by jibsonline** [comment]
Sorry..it turns out that i missed "." . I should have run `terraform destroy .` .  When i run without a "." it destroys only one file
