### ISSUE TITLE
Does not work with latest terraform (v0.8.8)

### ISSUE THREAD

**Issue by MohammedYunus** [oracle/terraform-provider-baremetal#22]
For some reason, I just can’t get terraform(v0.8.8) to execute even the simple example configuration

I followed all the steps for install terraform and BMCS terraform provider

When I execute terraform plan or apply I get the following error

$> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

I ran again after setting TF_LOG=1

2017/03/08 23:23:14 [ERROR] root: eval: *terraform.EvalConfigProvider, err: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5
2017/03/08 23:23:14 [ERROR] root: eval: *terraform.EvalSequence, err: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5
2017/03/08 23:23:14 [ERROR] root: eval: *terraform.EvalOpFilter, err: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5
2017/03/08 23:23:14 [ERROR] root: eval: *terraform.EvalSequence, err: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5
2017/03/08 23:23:14 [TRACE] [walkRefresh] Exiting eval tree: provider.baremetal

Is there any workaround for the above?

**Comment by jvcalise** [comment]
Please provide your TF file, and the OS you are running on.

**Comment by MohammedYunus** [comment]
Thanks. Regenerated the keys with no password. 

terraform now works
