### ISSUE TITLE
Unexpected state RESTORING error when creating Block Volume from Backup

### ISSUE THREAD

**Issue by jimmycal** [oracle/terraform-provider-baremetal#231]
Terraform Version

Terraform v0.9.6
&
Terraform v0.10.0

Baremetal Provider Version

terraform-provider-baremetal v1.0.17

Description:

When applying a configuration where I am creating a new volume from a backup I am encountering the following issue:

Error applying plan:

1 error(s) occurred:

* baremetal_core_volume.volume: 1 error(s) occurred:

* baremetal_core_volume.volume: unexpected state 'RESTORING', wanted target 'AVAILABLE'. last error: %!s(<nil>)

To reproduce this issue create a block volume backup if one doesn't already exist, no data has to existing on the volume backup and use the config below substitute your backup OCID.

terraform apply

Repro.tf

#BMC Provider Configuration
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}

provider "baremetal" {
region = "us-phoenix-1"
tenancy_ocid = "${var.tenancy_ocid}"
user_ocid = "${var.user_ocid}"
fingerprint = "${var.fingerprint}"
private_key_path = "${var.private_key_path}"
disable_auto_retries = "true"
}

resource "baremetal_core_volume" "volume" {
availability_domain = "pILZ:PHX-AD-2"
compartment_id = "${var.tenancy_ocid}"
display_name = "tf_test_volume" 
volume_backup_id = "ocid1.volumebackup.oc1.phx.abyhqljtg3v2ioezu24ityt5wrcjlstgb3v6naol5la5ldaserrlauw6ai4a"
}

**Comment by codycushing** [comment]
Fixed in v1.0.18

**Comment by jimmycal** [comment]
What is the planned delivery date of  1.0.18 ?  Can I get a drop of this version ASAP?

**Comment by briangustafson** [comment]
@jimmycal v1.0.18 with this fix has just been released.
