### ISSUE TITLE
Ability to extract public IP address

### ISSUE THREAD

**Issue by owainlewis** [oracle/terraform-provider-baremetal#25]
Is there a way to extract the public IP address when creating an instance?

The IP address is needed when running a remote provisioner.

E.g an AWS example

```
"${aws_instance.jenkins.public_ip}"
```

**Comment by jvcalise** [comment]
Yes, public/private IP is provided off of the VNIC interface for the instance once it is created - here is an example.  Create the instance, get the VNIC attachments, and then retrieve the details for the first VNIC.

resource "baremetal_core_instance" "hol" {
  availability_domain = "${var.ad_name}"
  compartment_id = "${var.compartment_name}"
  display_name = "${var.server_display_name}"
  image = "${var.image_name}"
  shape = "${var.shape_name}"
  subnet_id = "${var.subnet_name}"
  metadata {
    ssh_authorized_keys = "${var.public_key}"
    user_data = "${base64encode(file("${path.module}/HOL-CloudInit.yaml"))}"
  }
}

data "baremetal_core_vnic_attachments" "vnics" {
      compartment_id = "${var.compartment_name}"
      availability_domain = "${var.ad_name}"
      instance_id = "${baremetal_core_instance.hol.id}"
}

data "baremetal_core_vnic" "vnic" {
  vnic_id = "${lookup(data.baremetal_core_vnic_attachments.vnics.vnic_attachments[0],"vnic_id")}"
}

output "public_ip" {
  value = ["${data.baremetal_core_vnic.vnic.public_ip_address}"]
}

output "private_ip" {
  value = ["${data.baremetal_core_vnic.vnic.private_ip_address}"]
}

**Comment by owainlewis** [comment]
Thanks for the detailed response. Works great. :+1:
