### ISSUE TITLE
Appears to be a timing issue waiting for the subnets to delete causing other resource removal to fail

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-baremetal#3]
Running a "terraform apply" of the example complete_vcn.tf works perfectly.  However, when removing then environment with "terraform destroy", it appears to not wait long enough for the subnets to be removed before continuing to remove the other resources.  Therefore you need to run the "terraform destroy" a few times.

**Comment by craigcarl-oracle** [comment]
@PeterJamesHarrison We've confirmed an issue waiting for a subnet to transition to "TERMINATED".  A fix is in the works.
