### ISSUE TITLE
Timeout Error when creating Image

### ISSUE THREAD

**Issue by jvcalise** [oracle/terraform-provider-baremetal#30]
Seems like underlying SDK timeout for Available state is set too low for image creation.  We should offer timeout and state we want to wait for as parameters to the appropriate resources (instance, image)

module.omc-server.baremetal_core_image.bootstrap_image: Still creating... (5m0s elapsed)
Error applying plan:

1 error(s) occurred:

* baremetal_core_image.bootstrap_image: timeout while waiting for state to become 'AVAILABLE' (last state: 'PROVISIONING', timeout: 5m0s)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by craigcarl-oracle** [comment]
@jvcalise Is creating images a real use case for TF? I generally think of TF as a way to manage persistent infrastructure, is creating custom image a part of that?

If yes what should the default timeout be? You will be able to override the default via a TF variable.

**Comment by craigcarl-oracle** [comment]
Dup of #28
