### ISSUE TITLE
Provider should source credentials from the config file - 

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-baremetal#31]
If ~/.oraclebmc/config exists and the configuration doesn't specify alternative credentials then the provider should source credentials from .oraclebmc/config.

Example config file is here - https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdkconfig.htm

Config files support the concept of profiles. We should support a variable (obmcs_profile??) that can optionally be set to the profile to be used. If a TF configuration doesn't specify a profile then use [DEFAULT].

**Comment by craigcarl-oracle** [comment]
Here's a way we can do this outside of the provider, I think direct integration would be nicer.

https://gist.github.com/craigcarl-oracle/f00b14f86fc950fcdf14ea9a3e0136a9

**Comment by josephholsten** [comment]
@jhorwit2  pointed me at https://gist.github.com/jhorwit2/7f18873988fb6496592e280c7b56f699

**Comment by craigcarl-oracle** [comment]
We've decided this functionality should go in the SDK, not the provider. Once the re-factored SDK ships we'll re-evaluate.
