### ISSUE TITLE
Cannot create route tables with empty rule

### ISSUE THREAD

**Issue by byan888** [oracle/terraform-provider-baremetal#34]
We want to create route table with empty rule, UI allows 
creating the empty route tables without rules, so it seems that the API 
allows the empty route rule when creating route table, but so far I am 
not able to create the empty route table using terraform. 

sh-4.1$ terraform plan complete_vcn
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * baremetal_core_route_table.RouteForBastion: "route_rules.0.cidr_block": required field is not set
  * baremetal_core_route_table.RouteForBastion: "route_rules.0.network_entity_id": required field is not set
sh-4.1$ 

this is what I tried (removed the cidr_block and network_entity_id): 
resource "baremetal_core_route_table" "RouteForBastion" {
    compartment_id = "${var.compartment_ocid}"
    vcn_id = "${baremetal_core_virtual_network.adminphx1.id}"
    display_name = "bastion"
    route_rules {
        cidr_block = "0.0.0.0/0"
        network_entity_id = "${baremetal_core_internet_gateway.adminphx1IG.id}"
    }
}

**Comment by mahthi** [comment]
@craigcarl-oracle @mikejihbe Can you guys help taking a look at this issue?

**Comment by craigcarl-oracle** [comment]
Both `cidr_block` and `network_entity_id` are optional on the CreateRouteTableDetails API, should be optional in TF.
