### ISSUE TITLE
Error asking for user input: 1 error(s) occurred:  * provider.baremetal: Incompatible API version with plugin. Plugin version: 2, Ours: 4

### ISSUE THREAD

**Issue by chatchai-komrangded** [oracle/terraform-provider-baremetal#37]
For Unix
I've already create file ~/.terraformrc in Unix, but still get the error, here is my configuration:
[root@rac-omc2 ~]# pwd
/root
[root@rac-omc2 ~]# cat .terraformrc
providers {
  baremetal = "/root/infra-code/terraform-provider-baremetal"
  }

For Windows
I've already create file %APPDATA%/terraform.rc, but still get the error 
Error loading CLI configuration:
Error parsing C:\Users\ckomrang\AppData\Roaming\terraform.rc: At 2:19: illegal char escape

Here's my teraform.rc
providers {
  baremetal = "D:\infra-code\terraform-provider-baremetal.exe"
}

Any suggest for that?

**Comment by chatchai-komrangded** [comment]
Hi , I've fixed by downgrade teraform version to 0.88

**Comment by craigcarl-oracle** [comment]
Dup of #40
