### ISSUE TITLE
merge artifacts in main README.md and LICENSE.md

### ISSUE THREAD

**Issue by scross01** [oracle/terraform-provider-baremetal#4]
<<<<<<< HEAD

occurs several times in README.md and LICENSE.md

**Comment by scross01** [comment]
More files with "<<<<<<< HEAD" merge issues:

core_volume_test.go 
core/volume_resource.go 
core_volume_datasource_test.go 
core/volume_resource_crud.go

**Comment by craigcarl-oracle** [comment]
also found -
request_options.go
core_volume.go
vendor.json

fixed.
