### ISSUE TITLE
Need to upgrade plugin version to 4 - 

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-baremetal#40]
Our provider is compatible with TF > .7.7 and =< .8.8. Need to get to .9*.

**Comment by lfeldman** [comment]
I have been hit but this error yesterday and I was sure I will produced an issue here. But you have discovered it meanwhile so now I will just wait for it :)))

**Comment by craigcarl-oracle** [comment]
@codycushing you tested this, what was the required change(s)? @josephholsten, @mikejihbe want to get this done.

**Comment by josephholsten** [comment]
does this require anything besides `govendor fetch github.com/hashicorp/terraform/...`?
