### ISSUE TITLE
Provider doesn't support data source: baremetal_identity_availability_domains

### ISSUE THREAD

**Issue by srinatar** [oracle/terraform-provider-baremetal#5]
data "baremetal_identity_availability_domains" "t" {
  compartment_ocid = "${var.compartment_ocid}"
}

-> i do see a data source for API Keys. But, I do not see an equivalent definition for availability_domains. 
-> we need this because the availability domain string is unique for every tenancy. so, the current examples that refer to "Uocm" is specific to a tenancy and cannot be used for other tenancy.

**Comment by srinatar** [comment]
it will be nice if we can be able to do something like below 

ADs = ["${data.baremetal_identity_availability_domains.all.names}"]

and

AD1 = "${data.baremetal_identity_availability_domains.AD1.name}"

**Comment by craigcarl-oracle** [comment]
@srinatar Yes, that's a miss, I'll work on it.
