### ISSUE TITLE
Unable to assign custom DHCP Options to a subnet

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-baremetal#50]
Able to create custom DNS DHCP options, but not able to use dhcp_options_id attribute  in the resource "baremetal_core_subnet"

resource "baremetal_core_dhcp_options" "DHCP-Options" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
    display_name            = "Custom dhcp-1"
    options {
         type               = "DomainNameServer"
         server_type        = "CustomDnsServer"
         custom_dns_servers = [ "10.1.1.1","10.1.1.2","10.1.1.2" ]
         }
}

resource "baremetal_core_subnet" "WebSubnetAD1" {
  availability_domain = "${var.ADs[0]}"
  cidr_block = "10.45.1.0/24"
  display_name = "WebSubnetAD1"
  dhcp_options_id = "${baremetal_core_dhcp_options.DHCP-Options.id}"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
  security_list_ids = ["${baremetal_core_security_list.WebSubnet.id}"]
}

$ terraform plan work/terraform 
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * baremetal_core_subnet.WebSubnetAD1: : invalid or unknown key: dhcp_options_id

**Comment by craigcarl-oracle** [comment]
Confirmed
