### ISSUE TITLE
Ability to extract dns name of subnet

### ISSUE THREAD

**Issue by wplu** [oracle/terraform-provider-baremetal#51]
Is there a way to extract the DNS domain name when creating an instance?

The DNS domain name is needed to access other hosts on that subnet.

For example, if i created a host on the "ad1" subnet of the okedev vcn, I'd like to be able to extract its ad1.okedev.oraclevcn.com DNS domain name.

**Comment by craigcarl-oracle** [comment]
Soon, see #21.

Dup of #21.
