### ISSUE TITLE
Should load balancers require 2 subnets?

### ISSUE THREAD

**Issue by josephholsten** [oracle/terraform-provider-baremetal#52]
We've noticed that load balancers can be created in the API with a single subnet, but require two in the UI. Should the terraform provider require exactly 2 subnets when creating a load balancer?

**Comment by craigcarl-oracle** [comment]
@josephholsten I haven't tested this yet, the [documentation](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/loadbalancer/20170115/requests/CreateLoadBalancerDetails) indicates that subnetIds is an array -
```
subnetIds	
    Type: [string, ...]
An array of subnet OCIDs.
```

**Comment by josephholsten** [comment]
absolutely, I'm just wondering if we should have validation on the length of the array.

**Comment by jodoglevy** [comment]
@josephholsten I've engaged the Load Balancer service team to enforce this requirement server-side.

**Comment by jodoglevy** [comment]
@craigcarl-oracle LB team will be deploying a fix for this server-side in the next few days, so think we can close this.

**Comment by josephholsten** [comment]
I'll take responsibility for this one

**Comment by mikejihbe** [comment]
@josephholsten let's not change anything until the server side is updated.

**Comment by srinatar** [comment]
Mike - server side has been updated. sorry, we missed updating this thread.

**Comment by craigcarl-oracle** [comment]
Resolved
