### ISSUE TITLE
Ansible OBMC dynamic inventory

### ISSUE THREAD

**Issue by VAdamec** [oracle/terraform-provider-baremetal#55]
So far it support OpenStack, AWS, Mantl and others. Would be awesome to have support for Oracle BMC too. I could do that but it takes me a weeks, any volunteer ? :-) 

Original work is here https://github.com/CiscoCloud/terraform.py

**Comment by josephholsten** [comment]
This is awesome, but not on our set of priorities right now. If you want to take a stab at it, please let us know how it goes. We haven't officially locked in our terraform state format, but it's good to know that something else could be consuming it.

If you have any questions about the state data, let us know!

**Comment by VAdamec** [comment]
Very simple, but working: https://gist.github.com/VAdamec/a90a52bad95ce78d5fa8dbdf394077df

**Comment by VAdamec** [comment]
Closing, as there is no future progress. Feel free to use my modification of standard Cisco Systems, Inc. dynamic inventory.
