### ISSUE TITLE
Cannot create 2TB volume

### ISSUE THREAD

**Issue by mauropagano** [oracle/terraform-provider-baremetal#57]
Hi,

While trying to create a 2TB volumes I get the following error

* baremetal_core_volume.TFBlock0: invalid character '<' looking for beginning of value

while it works fine creating it 256GB.
The definition for the two sizes is coming from the example of the single instance and it's

variable "2TB" {
    default = "2097152"
}
variable "256GB" {
    default = "262144"
}

while the definition of the block volume is 

resource "baremetal_core_volume" "TFBlock0" {
  availability_domain = "${var.availability_domain}"
  compartment_id = "${var.compartment_ocid}"
  display_name = "TFBlock0"
  size_in_mbs = "${var.2TB}"
}

If I replace 2TB with 256GB then it works fine.
Interesting part is the 2TB volume is indeed created in my tenancy, just the error is raised too which is weird (and suggests some sort of syntax error I guess)

Thanks,
Mauro

**Comment by codycushing** [comment]
Hi @mauropagano I have reprod this, the service is returning 503 and an html error causing a json parsing error... and still creating the 2T volume. I will follow up internally on the latter and improve the error handling for 500 level errors in the plugin.

**Comment by craigcarl-oracle** [comment]
Resolved.

**Comment by mauropagano** [comment]
Craig,

sorry to comment on this one but I got a quick question.
I see no new file uploaded / modified to GitHub, does it mean the fix was only "internal" to your code or should I wait for a new release of the Terraform module to be uploaded here?

Cheers,
Mauro

**Comment by craigcarl-oracle** [comment]
@mauropagano No problem following up on a closed ticket at all. The problem was internal to the BMC API, this wasn't a provider issue.
