### ISSUE TITLE
db_system: continuous change for db parameters (no changes to configuration) cause error during apply

### ISSUE THREAD

**Issue by marcusdo** [oracle/terraform-provider-baremetal#58]
I deployed a new terraform database based on the DBsystems example posted on github.
The deployment was successful but when I run terraform plan again it always wants to change the following:
 
~ baremetal_database_db_system.DBsrv3AD3
    db_home.0.database.0.admin_password: "" => "BEstrO0ng_#11"
    db_home.0.database.0.db_name:        "" => "DBSWING1"
    db_home.0.db_version:                "" => "12.1.0.2"
    db_home.0.display_name:              "" => "DBSWING1"
 
Plan: 0 to add, 1 to change, 0 to destroy.
 
 
And during the apply I always get the following error:
 
baremetal_database_db_system.DBsrv3AD3: Refreshing state... (ID: ocid1.dbsystem.oc1.phx.abyhqljt2aox5j7puerbohtayb6w2fxinoc2ciqqkukg4okou6ihy2skflkq)
baremetal_database_db_system.DBsrv3AD3: Modifying...
  db_home.0.database.0.admin_password: "" => "BEstrO0ng_#11"
  db_home.0.database.0.db_name:        "" => "DBSWING1"
  db_home.0.db_version:                "" => "12.1.0.2"
  db_home.0.display_name:              "" => "DBSWING1"
Error applying plan:
 
1 error(s) occurred:
* baremetal_database_db_system.DBsrv3AD3: doesn't support update

The following workaround temporarily fixed the problem. Added the following to the resource:

  lifecycle {
   ignore_changes = ["db_home.0.database.0.admin_password","db_home.0.database.0.db_name","db_home.0.db_version","db_home.0.display_name"]
  }

**Comment by mikejihbe** [comment]
`ack schema.TypeList | grep -v vendor` will identify all our code that has lists in it, @craigcarl-oracle is going to identify which ones need treatment because they're immutable.

**Comment by mauropagano** [comment]
Hi,

I have the same exact problem, I understand the "doesn't support update" error and it seems fine to me. 
I think the problem is those 4 fields not being set at the first run
db_home.0.database.0.admin_password
db_home.0.database.0.db_name
db_home.0.db_version
db_home.0.display_name

Thanks,
Mauro

**Comment by craigcarl-oracle** [comment]
@mauropagano the workaround described the original comment works well. Does it unblock you?

**Comment by mauropagano** [comment]
Yeap it does!

Thanks guys,
Mauro

**Comment by craigcarl-oracle** [comment]
Fix will ship this week

**Comment by mikejihbe** [comment]
This is actually working for me just fine with the latest plugin version.

**Comment by craigcarl-oracle** [comment]
Fixed, please upgrade to the newest provider.
