### ISSUE TITLE
Removing all rules for security list (ie empty), changes do not apply

### ISSUE THREAD

**Issue by beamanm** [oracle/terraform-provider-baremetal#61]
When removing all rules from a security list, the apply shows the changes are commited but the security list is not actually changed.  I'm confirmed this via the portal that changes are not committed. Ex:

baremetal_core_security_list.internal-db1: Modifying...
  egress_security_rules.#:               "3" => "0"
  egress_security_rules.0.destination:   "192.168.0.0/19" => ""
  egress_security_rules.0.icmp_options:  "" => ""
  egress_security_rules.0.protocol:      "6" => ""
  egress_security_rules.0.stateless:     "" => ""
  egress_security_rules.0.tcp_options:   "" => ""
  egress_security_rules.0.udp_options:   "" => ""
  egress_security_rules.1.destination:   "192.168.0.0/19" => ""
  egress_security_rules.1.icmp_options:  "" => ""
  egress_security_rules.1.protocol:      "1" => ""
  egress_security_rules.1.stateless:     "" => ""
  egress_security_rules.1.tcp_options:   "" => ""
  egress_security_rules.1.udp_options:   "" => ""
  egress_security_rules.2.destination:   "192.168.0.0/19" => ""
  egress_security_rules.2.icmp_options:  "" => ""
  egress_security_rules.2.protocol:      "17" => ""
  egress_security_rules.2.stateless:     "" => ""
  egress_security_rules.2.tcp_options:   "" => ""
  egress_security_rules.2.udp_options:   "" => ""
  ingress_security_rules.#:              "3" => "0"
  ingress_security_rules.0.icmp_options: "" => ""
  ingress_security_rules.0.protocol:     "6" => ""
  ingress_security_rules.0.source:       "192.168.0.0/19" => ""
  ingress_security_rules.0.stateless:    "" => ""
  ingress_security_rules.0.tcp_options:  "" => ""
  ingress_security_rules.0.udp_options:  "" => ""
  ingress_security_rules.1.icmp_options: "" => ""
  ingress_security_rules.1.protocol:     "1" => ""
  ingress_security_rules.1.source:       "192.168.0.0/19" => ""
  ingress_security_rules.1.stateless:    "" => ""
  ingress_security_rules.1.tcp_options:  "" => ""
  ingress_security_rules.1.udp_options:  "" => ""
  ingress_security_rules.2.icmp_options: "" => ""
  ingress_security_rules.2.protocol:     "17" => ""
  ingress_security_rules.2.source:       "192.168.0.0/19" => ""
  ingress_security_rules.2.stateless:    "" => ""
  ingress_security_rules.2.tcp_options:  "" => ""
  ingress_security_rules.2.udp_options:  "" => ""
....
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
...
[RED ~/terraform/prod]$terraform plan
~ baremetal_core_security_list.internal-db1
    egress_security_rules.#:               "3" => "0"
    egress_security_rules.0.destination:   "192.168.0.0/19" => ""
    egress_security_rules.0.icmp_options:  "" => ""
    egress_security_rules.0.protocol:      "6" => ""
    egress_security_rules.0.stateless:     "" => ""
    egress_security_rules.0.tcp_options:   "" => ""
    egress_security_rules.0.udp_options:   "" => ""
    egress_security_rules.1.destination:   "192.168.0.0/19" => ""
    egress_security_rules.1.icmp_options:  "" => ""
    egress_security_rules.1.protocol:      "1" => ""
    egress_security_rules.1.stateless:     "" => ""
    egress_security_rules.1.tcp_options:   "" => ""
    egress_security_rules.1.udp_options:   "" => ""
    egress_security_rules.2.destination:   "192.168.0.0/19" => ""
    egress_security_rules.2.icmp_options:  "" => ""
    egress_security_rules.2.protocol:      "17" => ""
    egress_security_rules.2.stateless:     "" => ""
    egress_security_rules.2.tcp_options:   "" => ""
    egress_security_rules.2.udp_options:   "" => ""
    ingress_security_rules.#:              "3" => "0"
    ingress_security_rules.0.icmp_options: "" => ""
    ingress_security_rules.0.protocol:     "6" => ""
    ingress_security_rules.0.source:       "192.168.0.0/19" => ""
    ingress_security_rules.0.stateless:    "" => ""
    ingress_security_rules.0.tcp_options:  "" => ""
    ingress_security_rules.0.udp_options:  "" => ""
    ingress_security_rules.1.icmp_options: "" => ""
    ingress_security_rules.1.protocol:     "1" => ""
    ingress_security_rules.1.source:       "192.168.0.0/19" => ""
    ingress_security_rules.1.stateless:    "" => ""
    ingress_security_rules.1.tcp_options:  "" => ""
    ingress_security_rules.1.udp_options:  "" => ""
    ingress_security_rules.2.icmp_options: "" => ""
    ingress_security_rules.2.protocol:     "17" => ""
    ingress_security_rules.2.source:       "192.168.0.0/19" => ""
    ingress_security_rules.2.stateless:    "" => ""
    ingress_security_rules.2.tcp_options:  "" => ""
    ingress_security_rules.2.udp_options:  "" => ""

**Comment by josephholsten** [comment]
I'm taking this one

**Comment by craigcarl-oracle** [comment]
Resolved by [283440e](https://github.com/MustWin/terraform-provider-baremetal/commit/283440ebc9cb8f6c0d25fd30b8eecefcb1deced4).
