### ISSUE TITLE
default_dhcp_options_id not available on baremetal_core_virtual_network

### ISSUE THREAD

**Issue by tomzepf-oracle** [oracle/terraform-provider-baremetal#63]
I cannot reference the default dhcp options within subnet creation:

Error creating plan: 1 error(s) occurred:

* Resource 'baremetal_core_virtual_network.tzepf-vcn' does not have attribute 'default_dhcp_options_id' for variable 'baremetal_core_virtual_network.tzepf-vcn.default_dhcp_options_id'

**Comment by mikejihbe** [comment]
This is confirmed, I think this attribute was added a little later than the rest. We'll get it in.

**Comment by richlewis469** [comment]
We have also encountered this in GIT NGCC, is there anyway to enhance the map so that "terraform plan" will detect the potential change?
