### ISSUE TITLE
BM provider has issues with interpolation for identifying subnet ocid

### ISSUE THREAD

**Issue by jmajumde** [oracle/terraform-provider-baremetal#64]
The problem is BM provider for TF sometime gets confuse to understand the
subnet OCID via interpolation
..
.
Detailed Results of Problem Analysis:
"subnet_id": "${baremetal_core_subnet.mysubnet.id}",
.
- This definitions sometime throws illogical error like below
Error applying plan:
.
1 error(s) occurred:
.
* baremetal_core_instance.myAppVM: Code: InvalidParameter; OPC Request
ID: /xxxx/xxxx;
Message: The requested subnetId
ocid1.subnet.oc1.myregion.id is invalid: The Subnet does not exist or you are not authorized to access
it.

The above subnet is very much valid and I can use UI portal or backend sdks, apis to create instance in the same subnet.

Also If I change this definition from interpolation to actual ocid 

"subnet_id": "ocid1.subnet.oc1.myregion.id",
.
it works

**Comment by tomzepf-oracle** [comment]
I have also seen a variation of this. It looks like there is a race condition between when a subnet is completely ready for use and when terraform decides to proceeed with provisioning compute instances on the subnet. It always fixes itself if I just run "terraform apply" immediately after the failure.

**Comment by craigcarl-oracle** [comment]
@tomzepf-oracle what you are describing is a different issue, @jmajumde is attempting to interpolate a subnet OCID which can be difficult because of the way TF and OBMCS interact, I think we have a working pattern, just finishing up some testing. The issue you are describing is in the API, I filed a ticket a few days ago, I'll check progress.

**Comment by tomzepf-oracle** [comment]
Thanks for the clarification. Should I create a separate Issue to track?

**Comment by craigcarl-oracle** [comment]
We've tracked this down to a bug in the BMC API, we're working the issue. In the meantime there is a not-at-all pretty workaround, add a sleep to your subnet resources - 

#macOS
provisioner "local-exec" {
    command = "sleep 10"
   }

https://www.terraform.io/docs/provisioners/local-exec.html

**Comment by tomzepf-oracle** [comment]
Yes, not pretty, but the sleep workaround does work for now.

**Comment by devcamcar** [comment]
I'm also running into this consistently.  I added the sleep local-exec and even bumped it to 20 seconds but I still run into it occasionally.

**Comment by craigcarl-oracle** [comment]
@devcamcar We're asking eng for a sleep time that will cover 99.99% of subnet creations, I'll update the ticket when we get that.

**Comment by rahulviswam17** [comment]
Hi Craig, 

I've the below code block with a provisioner for sleep , but still running into the same error while re-running "terraform apply" . Am I doing something incorrect here? please advise. 


## Code Block 

resource "baremetal_core_subnet" "WebSubnetAD1" {
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.ADs.availability_domains[0],"name")}"
  cidr_block = "10.0.1.0/24"
  display_name = "EXT1"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
  security_list_ids = ["${baremetal_core_virtual_network.CompleteVCN.default_security_list_id}","${baremetal_core_security_list.CustmSecurityList.id}"]
  provisioner "local-exec" {
  command = "sleep 60"
  }

}

**Comment by devcamcar** [comment]
@rahulviswam17 That looks correct.  I checked and I have exact same format in my tests.  It could be something else.  Might get more help posting the rest of your .tf file.

**Comment by devcamcar** [comment]
@rahulviswam17, @craigcarl-oracle  Actually I just noticed that I'm still getting some occasional errors with a 60 second time out myself.

**Comment by craigcarl-oracle** [comment]
@devcamcar We've upped the priority on the issue, I'll let you know as soon as we have a timeline for a fix.

**Comment by rahulviswam17** [comment]
Thanks for increasing the priority Craig. 

@devcamcar , I've attached my tf file here.
[complete_vcn_network.txt](https://github.com/oracle/terraform-provider-baremetal/files/978263/complete_vcn_network.txt)
[complete_vcn_network.txt](https://github.com/oracle/terraform-provider-baremetal/files/978264/complete_vcn_network.txt)

**Comment by codycushing** [comment]
The answer to max reasonable subnet creation time is 1 minute for 99% of cases, 5 minutes for 99.99% of cases. The fix for properly reflecting subnet creation state is in progress.

**Comment by craigcarl-oracle** [comment]
Fixed at BMC API.
