### ISSUE TITLE
State mgmt for adding new compute vm/nodes gives confusing error for comp-id

### ISSUE THREAD

**Issue by jmajumde** [oracle/terraform-provider-baremetal#65]
While adding new compute VM for existing topology using TF templates gives wired error for subnet-id

Error applying plan:
.
2 error(s) occurred:
.
* baremetal_core_subnet.mydbsubnet: Code: NotAuthorizedOrNotFound; OPC
Request ID:
/xxxxx/xxxx; Message:
Either Subnet with ID
ocid1.compartment.oc1..mycompid does not exist or you are not authorized to access it.
* baremetal_core_subnet.myappssubnet: Code: NotAuthorizedOrNotFound; OPC
Request ID:
/xxxxxx/xxxx; Message:
Either Subnet with ID
ocid1.compartment.oc1..mycompid does not exist or you are not authorized to access it.

if you see the error some reason "baremetal_core_instance" things that for new VM nodes subnet id is the compartment id

Also I didnt ask BM provider to change anything related to my subnets but still it wants to change below 

~ baremetal_core_subnet.myappsubnet
    dhcp_options_id:
"ocid1.dhcpoptions.oc1.mydhcp"
.
~ baremetal_core_subnet.mydbsubnet
    dhcp_options_id:
"ocid1.dhcpoptions.oc1.mydhcp"
..
Plan: 2 to add, 2 to change, 0 to destroy.

I have asked in my tempalte to create 2 more app vm node in the "myappssubnet" but why its touching "mydbsubnet" ?

**Comment by craigcarl-oracle** [comment]
@jmajumde This looks like two issues - 
1. 404 on a subnet
2. DHCP options are being recreated without any changes in the configuration

On the 404 TF just uses the API and returns errors directly from the endpoint. If you are certain that the subnet exists and that the user TF is using has the required permissions please recreate the issue and email me the opc-request-id, I'll track it down. 

I believe the DHCP issue was resolved in 1.0.8, please try again with the newest release. If the issue persists please open a new issue, combining issues in a single report isn't ideal.
