### ISSUE TITLE
objectstorage for terraform backend state

### ISSUE THREAD

**Issue by tomzepf-oracle** [oracle/terraform-provider-baremetal#67]
Is there / will there be a baremetal backend ala consul/s3 to use for distributed state management? Is there another baremetal friendly strategy in mind?

This would be a great addition to the support already in the provider.

**Comment by craigcarl-oracle** [comment]
@tomzepf-oracle we're working on the next iteration now, interesting things coming soon!

**Comment by jlamillan** [comment]
This issue is closed, which makes this difficult to track. Can we get some sort of tracking issue for this feature request?
