### ISSUE TITLE
Terraform and object storage

### ISSUE THREAD

**Issue by nazarenofeito** [oracle/terraform-provider-baremetal#77]
I could not find an example of using a resource that is an object storage.
Is it possible to orchestrate the spawn of object storage buckets in the same way as with block storage devices?
Thank you.
Nazareno.

**Comment by devcamcar** [comment]
It looks that way: https://github.com/oracle/terraform-provider-baremetal/blob/master/objectstorage/bucket_resource.go

I don't believe there are examples in the docs though.

**Comment by codycushing** [comment]
There are no sample plans but there is example usage in docs:
https://github.com/oracle/terraform-provider-baremetal/tree/master/docs/resources/objectstorage
https://github.com/oracle/terraform-provider-baremetal/tree/master/docs/datasources/objectstorage
