### ISSUE TITLE
Unable to create virtual networks with v1.08 release

### ISSUE THREAD

**Issue by devcamcar** [oracle/terraform-provider-baremetal#79]
## Description of the bug:  Attempting to create VCNs with 1.08 results in error message "Invalid property name defaultDhcpOptionsId"

$ terraform apply
data.baremetal_core_images.OLImageOCID: Refreshing state...
data.baremetal_identity_availability_domains.ADs: Refreshing state...
baremetal_core_volume.TFBlock0: Refreshing state... (ID: ocid1.volume.oc1.phx.abyhqljtvhup5t72ix...ykugsjdex4w5wmajpbvlbpcgd2kct74hhcma5q)
baremetal_core_virtual_network.CloudFoundryVCN: Creating...
  cidr_block:               "" => "10.0.0.0/16"
  compartment_id:           "" => "ocid1.compartment.oc1..aaaaaaaaiiflgxfzgrmthjv4bv73vlkjdo7ojjqeez2ndms3jaloykp3m6wa"
  default_dhcp_options_id:  "" => "<computed>"
  default_route_table_id:   "" => "<computed>"
  default_security_list_id: "" => "<computed>"
  display_name:             "" => "CloudFoundryVCN"
  state:                    "" => "<computed>"
  time_created:             "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* baremetal_core_virtual_network.CloudFoundryVCN: 1 error(s) occurred:

* baremetal_core_virtual_network.CloudFoundryVCN: Code: InvalidParameter; OPC Request ID: /987DBD08DC954B2EB7A8D76EB9490F12/8F07C727D75848018C416501CD41CF10; Message: Invalid property name defaultDhcpOptionsId. Available property names are cidrBlock, compartmentId, displayName, dnsLabel

## A self-contained terraform file that reproduces the issue:
resource "baremetal_core_virtual_network" "TestVCN" {
  cidr_block = "10.0.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  display_name = "TestVCN"
}

**Comment by mikejihbe** [comment]
Confirmed, and duplicated in #81. Working on a fix now.
