### ISSUE TITLE
NetBSD binaries don't build - 

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-baremetal#8]
This is a bug in Terraform. A fix has been submitted to the project (https://github.com/hashicorp/terraform/pull/12138). Once the pull has been accepted and a new binary released we will ship NetBSD binaries.

**Comment by craigcarl-oracle** [comment]
TF merged the pull request, I'll build a new TF binary against that version and build new provider binaries with it.

**Comment by mikejihbe** [comment]
This should be included in v0.8.8 or v0.9. When you can build against an actual release, that will be preferable.

**Comment by craigcarl-oracle** [comment]
Not a target for TF, closing.
