### ISSUE TITLE
How do you configure Terraform to use Swift remote?

### ISSUE THREAD

**Issue by devcamcar** [oracle/terraform-provider-baremetal#80]
I am attempting to use Terraform's Swift support to store state against BMC's object store.  Here is what I have in my state.tf file:

    terraform {
      backend "swift" {
        path = "terraform"
        auth_url = "https://swiftobjectstorage.us-phoenix-1.oraclecloud.com/v1/mytenantname/"
        password = "myswiftpassword"
      }
    }

This appears to be correct but Terraform doesn't like it:

    $ terraform init
    Initializing the backend...

    Error configuring the backend "swift": Failed to configure remote backend "swift": Resource not found

    Please update the configuration in your Terraform files to fix this error then run this command again.

**Comment by craigcarl-oracle** [comment]
@devcamcar The Swift implementation on the BMC object store is limited; scoped only to support RMAN backups. That said I expect the features required to support the Swift TF backend have been implemented. Also, the error you are getting is too early for that. 

Please make sure you are running the newest BMC provider (v1.0.8) and TF version (v0.9.4).

Try `$ terraform init -backend=true`, see if that does it. When you get the backend initialized please let us know if our Swift implementation works. If it doesn't we have a S3 compatible API that's going to ship soon, I'm pretty sure that will work.

**Comment by devcamcar** [comment]
@craigcarl-oracle Thanks. I gave it another shot but still no luck:

    $ terraform init -backend=true
    Initializing the backend...

    Error configuring the backend "swift": Failed to configure remote backend "swift": Resource not found

    Please update the configuration in your Terraform files to fix this error
    then run this command again.

I think I have the URL wrong for the Swift endpoint.  It's not clear to me how the Swift implementation on BMCS handled authentication.  It's expecting a Keystone endpoint and to get the object store URL from Keystone's service catalog but I haven't been able to find documentation that explains this well on the BMCS side.

**Comment by josephholsten** [comment]
@devcamcar can you show us the output of `terraform version`?

BTW, the `swift` is in the core terraform project and isn't actually related to this codebase. I'll try to help, but you may have better luck over there.

**Comment by craigcarl-oracle** [comment]
@devcamcar Our SWIFT implementation only supports HTTP basic authentication; using curl a request would look like this -
`$ curl -v -u 'craig.carl@oracle.com:password' https://swiftobjectstorage.us-phoenix-1.oraclecloud.com/v1/<tenant_name>`

Also, the user you are using to auth with needs to be a tenant admin and the bucket needs to be in the root compartment.

**Comment by devcamcar** [comment]
Hi @craigcarl-oracle.  I suspect you're right and that Terraform doesn't support basic auth for it's Swift backend.

**Comment by craigcarl-oracle** [comment]
@devcamcar A S3 interface to the object store will ship soon, that will enable this.
