### ISSUE TITLE
Terraform: How to attach default Routing table and Security list to a subnet during a Complete VCN creation

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-baremetal#87]
## Description of the bug:
Hi, 

I need to attach default Route Table and and Default Security list to a subnet in a CompleteVCN creation template ? 

I tried the below code block but did not work. My VCN , IG etc are created as part of the same template file. 

## A self-contained terraform file that reproduces the issue:

##SubnetBlock

resource "baremetal_core_subnet" "WebSubnetAD1" {
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.ADs.availability_domains[0],"name")}"
  cidr_block = "10.0.1.0/24"
  display_name = "EXT1"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
  security_list_ids = ["${baremetal_core_virtual_network.CompleteVCN.default_security_list_id}","${baremetal_core_security_list.CustmSecurityList.id}"]
}

I also tried  below line of code for fetching the default security list ID :

 security_list_ids = ["${lookup(data.baremetal_core_virtual_network.CompleteVCN,"default_security_list_id")}","${baremetal_core_security_list.CustmSecurityList.id}"]

but I am able to see the default_security_list_id in my terraformstate file as below :

               "baremetal_core_virtual_network.CompleteVCN": {
                    "type": "baremetal_core_virtual_network",
                    "depends_on": [],
                    "primary": {
                        "id": "ocid1.vcn.oc1.phx.aaaaaaaaxodeebfu577doyusf5tefrmmevv5qokwydvu2ucowsdasicqmqvq",
                        "attributes": {
                            "cidr_block": "10.0.0.0/16",
                            "compartment_id": "ocid1.tenancy.oc1..aaaaaaaazqe56p5uw4ri7hzvmblb6jzwiuw6mdt7xgllx4vug3ttbyjtjuxq",
                            "default_route_table_id": "ocid1.routetable.oc1.phx.aaaaaaaachlcpl3gosgkax2loxyaoahb3noifqry4765six26uedmnj73ncq",
                            "default_security_list_id": "ocid1.securitylist.oc1.phx.aaaaaaaasncikoj6a5wqwi5iigngv5jogi42k7bb4rcdxgr5rd5vc4z2wqha",
                            "display_name": "TFCompleteVCN",
                            "id": "ocid1.vcn.oc1.phx.aaaaaaaaxodeebfu577doyusf5tefrmmevv5qokwydvu2ucowsdasicqmqvq",
                            "state": "AVAILABLE",
                            "time_created": "2017-05-03 02:18:09.924 +0000 UTC"

**Comment by craigcarl-oracle** [comment]
@rahulviswam17 The OCIDs of the default DHCP options, default route table, and default security list [are returned as attributes on the VCN resource.](https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/resources/core/virtual_networks.md)

So if you create `baremetal_core_virtual_network.CompleteVCN` you can reference those attributes as `baremetal_core_virtual_network.CompleteVCN.default_dhcp_options_id`, `baremetal_core_virtual_network.CompleteVCN.default_route_table_id`, `baremetal_core_virtual_network.CompleteVCN.default_security_list_id`.

**Comment by rahulviswam17** [comment]
Hi Craig , 

Thanks for your response. I've already tried attaching default_security_list_id from the reference attribute but it did not help. 

My requirement is to attach "2" security list ie 1) Default Security List and 2) a Custom Security list that I am creating explicitly in my template and attach both to my external subnet. 

I am pasting two code blocks that I tried, surprisingly both attempts attached only the "custom_security_list" for me. Please advise.

## CODE BLOCK (1)

resource "baremetal_core_subnet" "WebSubnetAD1" {
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.ADs.availability_domains[0],"name")}"
  cidr_block = "10.0.1.0/24"
  display_name = "EXT1"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
  security_list_ids = ["${baremetal_core_virtual_network.CompleteVCN.default_security_list_id}"]
}


## CODE BLOCK (2)

resource "baremetal_core_subnet" "WebSubnetAD1" {
  availability_domain = "${lookup(data.baremetal_identity_availability_domains.ADs.availability_domains[0],"name")}"
  cidr_block = "10.0.1.0/24"
  display_name = "EXT1"
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${baremetal_core_virtual_network.CompleteVCN.id}"
  route_table_id = "${baremetal_core_route_table.RouteForComplete.id}"
 security_list_ids = ["${baremetal_core_virtual_network.CompleteVCN.default_security_list_id}","${baremetal_core_security_list.CustmSecurityList.id}"]
}

**Comment by rahulviswam17** [comment]
Hi Craig , I've got it to working by using the CODE BLOCK (2) above. I call the template file in my main template file and it works as expected. Able to attach Default as well as custom routing table to the Subnet now.
